"""Create Pop, Rack, and RackSlot models

Revision ID: 701136364b27
Revises: 35809a291d70
Create Date: 2024-08-22 17:55:09.861526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701136364b27'
down_revision = '35809a291d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rack_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rack_slots')
    # ### end Alembic commands ###
