"""Create Pop, Rack, and RackSlot models

Revision ID: 35809a291d70
Revises: 03d802bf346f
Create Date: 2024-08-22 17:54:25.578052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35809a291d70'
down_revision = '03d802bf346f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_ru', sa.Integer(), nullable=False),
    sa.Column('max_kw', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pop_id'], ['pops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('racks')
    # ### end Alembic commands ###
