"""empty message

Revision ID: 25fbd939f79d
Revises: 56c4041b0191
Create Date: 2024-09-03 15:52:13.430065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fbd939f79d'
down_revision = '56c4041b0191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rack_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rack_slots', schema=None) as batch_op:
        batch_op.drop_column('slot_id')

    # ### end Alembic commands ###
