const cities = [
    { city: "New York", country: "USA", region: "North America" },
    { city: "Los Angeles", country: "USA", region: "North America" },
    { city: "Chicago", country: "USA", region: "North America" },
    { city: "Houston", country: "USA", region: "North America" },
    { city: "São Paulo", country: "Brazil", region: "South America" },
    { city: "Rio de Janeiro", country: "Brazil", region: "South America" },
    { city: "Buenos Aires", country: "Argentina", region: "South America" },
    { city: "London", country: "UK", region: "Europe" },
    { city: "Manchester", country: "UK", region: "Europe" },
    { city: "Paris", country: "France", region: "Europe" },
    { city: "Berlin", country: "Germany", region: "Europe" },
    { city: "Madrid", country: "Spain", region: "Europe" },
    { city: "Dublin", country: "Ireland", region: "Europe" },
    { city: "Tokyo", country: "Japan", region: "Asia" },
    { city: "Osaka", country: "Japan", region: "Asia" },
    { city: "Shanghai", country: "China", region: "Asia" },
    { city: "Beijing", country: "China", region: "Asia" },
    { city: "Hong Kong", country: "China", region: "Asia" },
    { city: "Seoul", country: "South Korea", region: "Asia" },
    { city: "Sydney", country: "Australia", region: "Australia" },
    { city: "Melbourne", country: "Australia", region: "Australia" },
    { city: "Brisbane", country: "Australia", region: "Australia" },
    { city: "Auckland", country: "New Zealand", region: "Australia" },
    { city: "Cape Town", country: "South Africa", region: "Africa" },
    { city: "Johannesburg", country: "South Africa", region: "Africa" },
    { city: "Nairobi", country: "Kenya", region: "Africa" },
    { city: "Lagos", country: "Nigeria", region: "Africa" },
    { city: "Cairo", country: "Egypt", region: "Africa" },
    { city: "Istanbul", country: "Turkey", region: "Europe/Asia" },
    { city: "Dubai", country: "UAE", region: "Asia" },
    { city: "Mumbai", country: "India", region: "Asia" },
    { city: "Delhi", country: "India", region: "Asia" },
    { city: "Bangkok", country: "Thailand", region: "Asia" },
    { city: "Singapore", country: "Singapore", region: "Asia" },
    { city: "Ho Chi Minh City", country: "Vietnam", region: "Asia" },
    { city: "Jakarta", country: "Indonesia", region: "Asia" },
    { city: "Manila", country: "Philippines", region: "Asia" },
    { city: "Kuala Lumpur", country: "Malaysia", region: "Asia" },
    { city: "Sao Paulo", country: "Brazil", region: "South America" },
    { city: "Rio de Janeiro", country: "Brazil", region: "South America" },
    { city: "Buenos Aires", country: "Argentina", region: "South America" },
    { city: "Lima", country: "Peru", region: "South America" },
    { city: "Santiago", country: "Chile", region: "South America" },
    { city: "Bogotá", country: "Colombia", region: "South America" },
    { city: "Caracas", country: "Venezuela", region: "South America" },
    { city: "Montevideo", country: "Uruguay", region: "South America" },
    { city: "San Juan", country: "Puerto Rico", region: "North America" },
    { city: "Toronto", country: "Canada", region: "North America" },
    { city: "Vancouver", country: "Canada", region: "North America" },
    { city: "Montreal", country: "Canada", region: "North America" },
    { city: "Calgary", country: "Canada", region: "North America" },
    { city: "Edmonton", country: "Canada", region: "North America" },
    { city: "Halifax", country: "Canada", region: "North America" },
    { city: "Ottawa", country: "Canada", region: "North America" },
    { city: "Quebec City", country: "Canada", region: "North America" },
    { city: "Winnipeg", country: "Canada", region: "North America" },
    { city: "Victoria", country: "Canada", region: "North America" },
    { city: "Zurich", country: "Switzerland", region: "Europe" },
    { city: "Geneva", country: "Switzerland", region: "Europe" },
    { city: "Vienna", country: "Austria", region: "Europe" },
    { city: "Prague", country: "Czech Republic", region: "Europe" },
    { city: "Warsaw", country: "Poland", region: "Europe" },
    { city: "Budapest", country: "Hungary", region: "Europe" },
    { city: "Bratislava", country: "Slovakia", region: "Europe" },
    { city: "Ljubljana", country: "Slovenia", region: "Europe" },
    { city: "Sarajevo", country: "Bosnia and Herzegovina", region: "Europe" },
    { city: "Belgrade", country: "Serbia", region: "Europe" },
    { city: "Zagreb", country: "Croatia", region: "Europe" },
    { city: "Riga", country: "Latvia", region: "Europe" },
    { city: "Tallinn", country: "Estonia", region: "Europe" },
    { city: "Vilnius", country: "Lithuania", region: "Europe" },
    { city: "Chisinau", country: "Moldova", region: "Europe" },
    { city: "Bucharest", country: "Romania", region: "Europe" },
    { city: "Sofia", country: "Bulgaria", region: "Europe" },
    { city: "Tbilisi", country: "Georgia", region: "Europe/Asia" },
    { city: "Yerevan", country: "Armenia", region: "Europe/Asia" },
    { city: "Baku", country: "Azerbaijan", region: "Europe/Asia" },
    { city: "Bishkek", country: "Kyrgyzstan", region: "Asia" },
    { city: "Almaty", country: "Kazakhstan", region: "Asia" },
    { city: "Astana", country: "Kazakhstan", region: "Asia" },
    { city: "Ulaanbaatar", country: "Mongolia", region: "Asia" },
    { city: "Dhaka", country: "Bangladesh", region: "Asia" },
    { city: "Karachi", country: "Pakistan", region: "Asia" },
    { city: "Lahore", country: "Pakistan", region: "Asia" },
    { city: "Islamabad", country: "Pakistan", region: "Asia" },
    { city: "Kathmandu", country: "Nepal", region: "Asia" },
    { city: "Colombo", country: "Sri Lanka", region: "Asia" },
    { city: "Male", country: "Maldives", region: "Asia" },
    { city: "Kabul", country: "Afghanistan", region: "Asia" },
    { city: "Muscat", country: "Oman", region: "Asia" },
    { city: "Doha", country: "Qatar", region: "Asia" },
    { city: "Riyadh", country: "Saudi Arabia", region: "Asia" },
    { city: "Jeddah", country: "Saudi Arabia", region: "Asia" },
    { city: "Tel Aviv", country: "Israel", region: "Asia" },
    { city: "Beirut", country: "Lebanon", region: "Asia" },
    { city: "Amman", country: "Jordan", region: "Asia" },
    { city: "Damascus", country: "Syria", region: "Asia" },
    { city: "Baghdad", country: "Iraq", region: "Asia" },
    { city: "Tehran", country: "Iran", region: "Asia" },
    { city: "Dubai", country: "UAE", region: "Asia" },
    { city: "Sharjah", country: "UAE", region: "Asia" },
    { city: "Abu Dhabi", country: "UAE", region: "Asia" },
    { city: "Kuwait City", country: "Kuwait", region: "Asia" },
    { city: "Manama", country: "Bahrain", region: "Asia" },
    { city: "Moscow", country: "Russia", region: "Europe/Asia" },
    { city: "Saint Petersburg", country: "Russia", region: "Europe/Asia" },
    { city: "Novosibirsk", country: "Russia", region: "Europe/Asia" },
    { city: "Yekaterinburg", country: "Russia", region: "Europe/Asia" },
    { city: "Nizhny Novgorod", country: "Russia", region: "Europe/Asia" },
    { city: "Kazan", country: "Russia", region: "Europe/Asia" },
    { city: "Samara", country: "Russia", region: "Europe/Asia" },
    { city: "Omsk", country: "Russia", region: "Europe/Asia" },
    { city: "Ufa", country: "Russia", region: "Europe/Asia" },
    { city: "Volgograd", country: "Russia", region: "Europe/Asia" },
    { city: "Krasnodar", country: "Russia", region: "Europe/Asia" },
    { city: "Minsk", country: "Belarus", region: "Europe" },
    { city: "Kyiv", country: "Ukraine", region: "Europe" },
    { city: "Chisinau", country: "Moldova", region: "Europe" },
    { city: "Bucharest", country: "Romania", region: "Europe" },
    { city: "Sofia", country: "Bulgaria", region: "Europe" },
    { city: "Tbilisi", country: "Georgia", region: "Europe/Asia" },
    { city: "Yerevan", country: "Armenia", region: "Europe/Asia" },
    { city: "Baku", country: "Azerbaijan", region: "Europe/Asia" },
    { city: "Tashkent", country: "Uzbekistan", region: "Asia" },
    { city: "Ashgabat", country: "Turkmenistan", region: "Asia" },
    { city: "Dushanbe", country: "Tajikistan", region: "Asia" },
    { city: "Vientiane", country: "Laos", region: "Asia" },
    { city: "Hanoi", country: "Vietnam", region: "Asia" },
    { city: "Manila", country: "Philippines", region: "Asia" },
    { city: "Kuala Lumpur", country: "Malaysia", region: "Asia" },
    { city: "Singapore", country: "Singapore", region: "Asia" },
    { city: "Hong Kong", country: "China", region: "Asia" },
    { city: "Taipei", country: "Taiwan", region: "Asia" },
    { city: "Seoul", country: "South Korea", region: "Asia" },
    { city: "Jakarta", country: "Indonesia", region: "Asia" },
    { city: "Bangkok", country: "Thailand", region: "Asia" },
    { city: "Dhaka", country: "Bangladesh", region: "Asia" },
    { city: "Karachi", country: "Pakistan", region: "Asia" },
    { city: "Lahore", country: "Pakistan", region: "Asia" },
    { city: "Islamabad", country: "Pakistan", region: "Asia" },
    { city: "Kathmandu", country: "Nepal", region: "Asia" },
    { city: "Colombo", country: "Sri Lanka", region: "Asia" },
    { city: "Male", country: "Maldives", region: "Asia" },
    { city: "Kabul", country: "Afghanistan", region: "Asia" },
    { city: "Muscat", country: "Oman", region: "Asia" },
    { city: "Doha", country: "Qatar", region: "Asia" },
    { city: "Riyadh", country: "Saudi Arabia", region: "Asia" },
    { city: "Jeddah", country: "Saudi Arabia", region: "Asia" },
    { city: "Tel Aviv", country: "Israel", region: "Asia" },
    { city: "Beirut", country: "Lebanon", region: "Asia" },
    { city: "Amman", country: "Jordan", region: "Asia" },
    { city: "Damascus", country: "Syria", region: "Asia" },
    { city: "Baghdad", country: "Iraq", region: "Asia" },
    { city: "Tehran", country: "Iran", region: "Asia" },
    { city: "Dubai", country: "UAE", region: "Asia" },
    { city: "Sharjah", country: "UAE", region: "Asia" },
    { city: "Abu Dhabi", country: "UAE", region: "Asia" },
    { city: "Kuwait City", country: "Kuwait", region: "Asia" },
    { city: "Manama", country: "Bahrain", region: "Asia" },
    { city: "Moscow", country: "Russia", region: "Europe/Asia" },
    { city: "Saint Petersburg", country: "Russia", region: "Europe/Asia" },
    { city: "Novosibirsk", country: "Russia", region: "Europe/Asia" },
    { city: "Yekaterinburg", country: "Russia", region: "Europe/Asia" },
    { city: "Nizhny Novgorod", country: "Russia", region: "Europe/Asia" },
    { city: "Kazan", country: "Russia", region: "Europe/Asia" },
    { city: "Samara", country: "Russia", region: "Europe/Asia" },
    { city: "Omsk", country: "Russia", region: "Europe/Asia" },
    { city: "Ufa", country: "Russia", region: "Europe/Asia" },
    { city: "Volgograd", country: "Russia", region: "Europe/Asia" },
    { city: "Krasnodar", country: "Russia", region: "Europe/Asia" },
    { city: "Minsk", country: "Belarus", region: "Europe" },
    { city: "Kyiv", country: "Ukraine", region: "Europe" },
    { city: "Chisinau", country: "Moldova", region: "Europe" },
    { city: "Bucharest", country: "Romania", region: "Europe" },
    { city: "Sofia", country: "Bulgaria", region: "Europe" },
    { city: "Tbilisi", country: "Georgia", region: "Europe/Asia" },
    { city: "Yerevan", country: "Armenia", region: "Europe/Asia" },
    { city: "Baku", country: "Azerbaijan", region: "Europe/Asia" },
    { city: "Tashkent", country: "Uzbekistan", region: "Asia" },
    { city: "Ashgabat", country: "Turkmenistan", region: "Asia" },
    { city: "Dushanbe", country: "Tajikistan", region: "Asia" },
    { city: "Vientiane", country: "Laos", region: "Asia" },
    { city: "Hanoi", country: "Vietnam", region: "Asia" },
    { city: "Manila", country: "Philippines", region: "Asia" },
    { city: "Kuala Lumpur", country: "Malaysia", region: "Asia" },
    { city: "Singapore", country: "Singapore", region: "Asia" },
    { city: "Hong Kong", country: "China", region: "Asia" },
    { city: "Taipei", country: "Taiwan", region: "Asia" },
    { city: "Seoul", country: "South Korea", region: "Asia" },
    { city: "Jakarta", country: "Indonesia", region: "Asia" },
    { city: "Bangkok", country: "Thailand", region: "Asia" },
    { city: "Dhaka", country: "Bangladesh", region: "Asia" },
    { city: "Karachi", country: "Pakistan", region: "Asia" },
    { city: "Lahore", country: "Pakistan", region: "Asia" },
    { city: "Islamabad", country: "Pakistan", region: "Asia" },
    { city: "Kathmandu", country: "Nepal", region: "Asia" },
  ]



// Create a Set to track unique cities
const seenCities = new Set();
const uniqueCities = cities.filter(city => {
    const key = `${city.city}-${city.country}`; // Use a unique key for each city
    if (seenCities.has(key)) {
        return false;
    } else {
        seenCities.add(key);
        return true;
    }
});

// Export the unique cities
export default uniqueCities;
